name: 2.1$(rev:.r) # build numbering format



jobs:
- job: 'BuildAndPublishToNuGet'
  steps:
  - template: AzureDevOps/Templates/StepTemplates/NetCore/Initialize_And_Test.yaml@ALMStuff
    parameters:
      buildConfiguration: $(buildConfiguration)
  - template: AzureDevOps/Templates/StepTemplates/NetCore/Pack_And_Publish_To_NuGet.yaml@ALMStuff
    parameters:
      folderToPack: $(folderToPack)
